### PR TITLE
Update js-toxcore-c to new toxencryptsave API.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/js-toxcore-c/5)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/js-toxcore-c/5#-:-K_RDMFlQqZmcyz1mIcZ:bg7igkv)*

**Comment by GrayHatter** [comment]
:lgtm_cancel: while I read why the tests are failing

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/js-toxcore-c/5#-:-K_RDapvt0d601BJyAO6:b-tekw8s)*

**Comment by GrayHatter** [comment]
Some of the tests that failed are written with incorrect assumptions about how toxcore should work. Others may need to be updated.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/js-toxcore-c/5#-:-K_RHw-yBQsM8nzyoFOE:bgjii4o)*

**Comment by iphydf** [comment]
@GrayHatter fixed.

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/js-toxcore-c/5#-:-K_muSNPkwavGGGrGhq-:bg7igkv)*

**Pull request merged**
